Error = 'ERROR!'

navbar_error = 'div navabar not found'
login_link_error = 'login link does not found'
register_link_error = 'register link not found'
homepage_link_error = 'homepage link not found'
homepage_href_error = 'homepage href is not correct'
edit_profile_link_error = 'edit profile link not found'
form_div_error = "form not found"
fields_not_found = "required fields not found"
profile_link_error = "profile link not found"
first_name_filed_error = "first name field not correct"
last_name_field_error = "last name field not correct"
user_name_filed_error = "username field not correct"
first_name_change_error = 'error in changing first_name'
last_name_change_error = 'error in changing last_name'
login_failed = "login failed"
contact_us_link_error = "Contact us link not found"
text_error = "text error not handled"
message_not_send = 'Message not sent'
logout_link_error = "Logout link not found"
logout_failed = "logout failed"
make_new_course_link_error = 'make_new_course link not found'
courses_link_error = 'courses link not found'
course_did_not_make = 'course did not make'
course_number_error = 'course number in div in not correct'
lecturer_error = 'lecturer in div in not correct'
course_name_error = 'course name in div in not correct'
course_box_error = 'course div not found'
lecturer_box_error = 'lecturer box not found'
college_box_error = 'department box not found'
have_not_all_inputs = 'have not all inputs'
submit_button_not_found = 'submit button not found'
can_not_search = 'can not search'
search_result_div_error = "div with \"search_result\" id not found"
result_not_found = "Not found all the expected results"
more_result_found = "Found an unexpected result in search result"
all_course_div_error = "div with \"all_courses\" id not found"
add_button_error = 'add button not found'
add_link_error = 'add link not found'
fail_to_get_course = ' fail to get course'
my_courses_div_error = "div with \"my_courses\" id not found"
course_not_found_in_my_courses = "added course not found in my_course div"
taken_course_found = 'taken course found in all_courses'
fail_to_show_error = 'failed to show error'
show_incorrect_error = 'show incorrect error'
comment_div_error = 'comments div not found'
comment_form_error = 'comment form not found'
fail_to_comment = 'fail to comment'
comment_failed = 'comment not found'
student_number_paragraph = 'p student_number not found'
student_number_error = 'student number is not correct'
user_not_found_in_db = "User is not created in database"
register_error = "Can not register"
register_with_existing_username = "must not register with already existing username"
register_with_wrong_passes = "must not register if password1 and password2 don't match"
error_div_error = "Div with \"errors\" id not found"
mail_server_error = "could not connect to mail server"
mail_title_incorrect = "email with desired title not found"
mail_content_incorrect = "email content is incorrect"
panel_link_error = "Panel link is not correct"
panel_page_error = "Panel page not working properly"
new_course_non_admin_error = "link to new course page is visible with non admin user"
new_course_admin_error = "link to new course page is not visible with admin user"
search_form_error = "search form not found"
file_input_field_error = "input field with \"file\" type not found"
img_tag_error = "img tag with \"profile_image\" id not found"
profile_image_error = "profile image is not the uploaded image"
img_src_error = "img src attribute not found"
remove_link_not_found = "remove link not found"
can_not_remove = "cannot remove course"
removed_course_still_in_my_course = "removed course is still in my_course div"
removed_course_not_in_all_course = "removed course not found in all_course div"
details_link_not_found = "details link not found"
course_div_error = "course div not found"
markdown_checkbox_not_found = "markdown checkbox not found"
markdown_comment_error = "markdown comment is incorrect"
panel_link_visible_error = "Panel link is shown when user is not logged in"
department_name_error = 'department is div is not correct'
time_error = 'course_time in div is not correct'
welcome_error = "Welcome text not found"
redirect_failed = "Could not redirect"
duplicate_search = "found duplicate in search result"
